name: demo ci

on:
 workflow_dispatch:

jobs:

 build-using-maven:
   runs-on: hello
   steps:
     - name: Checkout
       uses: actions/checkout@v6.0.1

     - name: print working directory
       run: pwd
